import { ENV } from "./env";

export const MAILER_CONFIG = {
    MAILER_SERVICE: ENV.MAILER_SERVICE,
    MAILER_USER: ENV.MAILER_USER,
    MAILER_EMAIL: ENV.MAILER_EMAIL,
    MAILER_PASSWORD: ENV.MAILER_PASSWORD
}