name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install prod dependencies
        run: npm ci

      - name: Generate prod ENV file
        run: |
          cat<<EOF > .env.prod
          PORT=${{ secrets.PROD_PORT }}
          MAILER_SERVICE=${{ secrets.PROD_MAILER_SERVICE }}
          MAILER_USER=${{ secrets.PROD_MAILER_USER }}
          MAILER_EMAIL=${{ secrets.PROD_MAILER_EMAIL }}
          MAILER_PASSWORD=${{ secrets.PROD_MAILER_PASSWORD }}
          GITHUB_ACCESS_TOKEN=${{ secrets.PROD_GITHUB_ACCESS_TOKEN }}
          GITHUB_USERNAME=${{ secrets.PROD_GITHUB_USERNAME }}
          DB_HOST=${{ secrets.PROD_DB_HOST }}
          DB_PORT=${{ secrets.PROD_DB_PORT }}
          DB_DATABASE=${{ secrets.PROD_DB_DATABASE }}
          DB_USER=${{ secrets.PROD_DB_USER }}
          DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}
          EOF

      - name: Build backend
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          include-hidden-files: true
          path: |
            dist/
            package.json
            package-lock.json
            .env.prod

  test:
    name: Test API
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: backend-dist

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: backend-dist

      - name: Run tests
        run: |
          npm run test
        working-directory: backend-dist

  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: backend-dist

      - name: SCP to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_INSTANCE_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            backend-dist/**
          target: ${{ secrets.PROD_APP_DIR }}
          rm: true

      - name: Restart portfolio-backend service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_INSTANCE_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mv ${{ secrets.PROD_APP_DIR }}/backend-dist temp
            rm -rf ${{ secrets.PROD_APP_DIR }}
            mv temp ${{ secrets.PROD_APP_DIR }}
            cd ${{ secrets.PROD_APP_DIR }}
            npm ci --omit=dev
            pm2 restart portfolio-backend || pm2 start ${{ secrets.PROD_APP_DIR }}/dist/app.js --name portfolio-backend
